name: remote ssh command
on: [push]

jobs:
  build: # First job
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: | 
            cd /var/www/LearnEnglishApp/
            git fetch origin main
            sudo git pull
            cat /var/www/LearnEnglishApp/.github/workflows/superlineter.yaml
